### PR TITLE
Update script

### PR DESCRIPTION
**Pull request by arthuro555**
Updated script to:
- Use MQTT instead to listen to the club status
- Add an ntfy.sh curl to send notifications to people when the club status changes too

### CODE REVIEW

**Comment by madonius** [comment]
@arthuro555 thanks for the PR, and sorry for the delay ^^'
In the future, poking somebody™ would be advisable.

@jcgruenhage how do we feel about sending the status to ntfy.sh, I personally see no issue per se.

**Review by madonius — APPROVED** [review]
lgtm

**Comment by arthuro555** [comment]
ping

**Comment by jcgruenhage** [comment]
@madonius machst du hier weiter? Wolltest du das nicht übernehmen und hosten?

**Pull request merged**
